// <auto-generated />
using System;
using LuanVan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuanVan.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuanVan.Model.BaoHiemDonVanChuyen", b =>
                {
                    b.Property<int>("MaBaoHiemDonVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoHiemDonVanChuyen"));

                    b.Property<float>("GiaTriBatDau")
                        .HasColumnType("real");

                    b.Property<float>("GiaTriKetThuc")
                        .HasColumnType("real");

                    b.Property<float>("PhiBaoHiem")
                        .HasColumnType("real");

                    b.HasKey("MaBaoHiemDonVanChuyen");

                    b.ToTable("BaoHiemDonVanChuyen");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietCuocPhi", b =>
                {
                    b.Property<long?>("MaCuocPhi")
                        .HasColumnType("bigint");

                    b.Property<long?>("MaQuanHuyen")
                        .HasColumnType("bigint");

                    b.HasKey("MaCuocPhi", "MaQuanHuyen");

                    b.HasIndex("MaQuanHuyen");

                    b.ToTable("ChiTietCuocPhi");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietDonVanChuyen", b =>
                {
                    b.Property<int>("MaChiTietDonVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonVanChuyen"));

                    b.Property<float>("ChieuCao")
                        .HasColumnType("real");

                    b.Property<float>("ChieuDai")
                        .HasColumnType("real");

                    b.Property<float>("ChieuRong")
                        .HasColumnType("real");

                    b.Property<float>("GiaTri")
                        .HasColumnType("real");

                    b.Property<int>("MaDonVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiMatHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("TrongLuong")
                        .HasColumnType("real");

                    b.HasKey("MaChiTietDonVanChuyen");

                    b.HasIndex("MaDonVanChuyen");

                    b.HasIndex("MaLoaiMatHang");

                    b.ToTable("ChiTietDonVanChuyen");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietTrangThai", b =>
                {
                    b.Property<int>("MaDonVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaTrangThaiDonVanChuyen")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonVanChuyen", "MaTrangThaiDonVanChuyen", "ThoiGian");

                    b.HasIndex("MaTrangThaiDonVanChuyen");

                    b.ToTable("ChiTietTrangThai");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietVaiTro", b =>
                {
                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaQuyen", "MaVaiTro");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("ChiTietVaiTro");
                });

            modelBuilder.Entity("LuanVan.Model.CoVaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaVaiTro", "MaTaiKhoan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("CoVaiTro");
                });

            modelBuilder.Entity("LuanVan.Model.CuocPhi", b =>
                {
                    b.Property<long>("MaCuocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaCuocPhi"));

                    b.Property<float>("GiaCuoc")
                        .HasColumnType("real");

                    b.Property<int>("MaHinhThucVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaTrongLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianGiao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCuocPhi");

                    b.HasIndex("MaHinhThucVanChuyen");

                    b.HasIndex("MaTrongLuong");

                    b.ToTable("CuocPhi");
                });

            modelBuilder.Entity("LuanVan.Model.DonVanChuyen", b =>
                {
                    b.Property<int>("MaDonVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonVanChuyen"));

                    b.Property<float>("CuocPhi")
                        .HasColumnType("real");

                    b.Property<string>("DiaChiNguoiGui")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChiNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBaoHiemDonVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaHinhThucVanChuyen")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhanVienGiaoHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaQuanLy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVanDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("MaXaPhuong")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToanCuocPhi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToanPhiNhanVienGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToanTienThuHo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToanTienThuHoKh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NguoiTraCuoc")
                        .HasColumnType("bit");

                    b.Property<float?>("PhiNhanVienGiaoHang")
                        .HasColumnType("real");

                    b.Property<string>("SoDienThoaiNguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiGui")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThoiGianGiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TongTienThuHo")
                        .HasColumnType("real");

                    b.Property<float>("TongTrongLuong")
                        .HasColumnType("real");

                    b.Property<long?>("XaPhuongMaXaPhuong")
                        .HasColumnType("bigint");

                    b.Property<bool>("YeuCauLayHang")
                        .HasColumnType("bit");

                    b.HasKey("MaDonVanChuyen");

                    b.HasIndex("MaBaoHiemDonVanChuyen");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVienGiaoHang");

                    b.HasIndex("MaQuanLy");

                    b.HasIndex("XaPhuongMaXaPhuong");

                    b.ToTable("DonVanChuyen");
                });

            modelBuilder.Entity("LuanVan.Model.DuLieuTinhCuoc", b =>
                {
                    b.Property<int>("MaDuLieuTinhCuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuLieuTinhCuoc"));

                    b.Property<float>("GiaCuocNac")
                        .HasColumnType("real");

                    b.Property<float>("GiaTriNac")
                        .HasColumnType("real");

                    b.Property<int>("MaHinhThucVanChuyen")
                        .HasColumnType("int");

                    b.Property<int>("MaTinhThanhPho")
                        .HasColumnType("int");

                    b.Property<float>("PhiTangNhanVienGiaoHang")
                        .HasColumnType("real");

                    b.Property<float>("TrongLuongBatDau")
                        .HasColumnType("real");

                    b.HasKey("MaDuLieuTinhCuoc");

                    b.HasIndex("MaHinhThucVanChuyen");

                    b.HasIndex("MaTinhThanhPho");

                    b.ToTable("DuLieuTinhCuoc");
                });

            modelBuilder.Entity("LuanVan.Model.HinhThucVanChuyen", b =>
                {
                    b.Property<int>("HinhThucVanCHuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHinhThucVanChuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HinhThucVanCHuyenId"));

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("MucChia")
                        .HasColumnType("real");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("HinhThucVanCHuyenId");

                    b.ToTable("HinhThucVanChuyen");
                });

            modelBuilder.Entity("LuanVan.Model.LoaiMatHang", b =>
                {
                    b.Property<int>("MaLoaiMatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiMatHang"));

                    b.Property<float>("KichThuocToiDa")
                        .HasColumnType("real");

                    b.Property<string>("MoTaLoaiMatHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PhuPhiMatHang")
                        .HasColumnType("real");

                    b.Property<string>("TenLoaiMatHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiMatHang");

                    b.ToTable("LoaiMatHang");
                });

            modelBuilder.Entity("LuanVan.Model.MatHangCaNhan", b =>
                {
                    b.Property<int>("MaMatHangCaNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMatHangCaNhan"));

                    b.Property<float>("ChieuCao")
                        .HasColumnType("real");

                    b.Property<float>("ChieuDai")
                        .HasColumnType("real");

                    b.Property<float>("ChieuRong")
                        .HasColumnType("real");

                    b.Property<bool>("Duyet")
                        .HasColumnType("bit");

                    b.Property<float>("GiaTri")
                        .HasColumnType("real");

                    b.Property<int>("MaLoaiMatHang")
                        .HasColumnType("int");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMatHangCaNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("TrongLuong")
                        .HasColumnType("real");

                    b.HasKey("MaMatHangCaNhan");

                    b.HasIndex("MaLoaiMatHang");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("MatHangCaNhan");
                });

            modelBuilder.Entity("LuanVan.Model.NguoiNhanCaNhan", b =>
                {
                    b.Property<int>("MaNguoiNhanCaNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiNhanCaNhan"));

                    b.Property<string>("DiaChiNguoiNhanCaNhan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("MaXaPhuong")
                        .HasColumnType("bigint");

                    b.Property<string>("SoDienThoaiCaNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhanCaNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiNhanCaNhan");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("MaXaPhuong");

                    b.ToTable("NguoiNhanCaNhan");
                });

            modelBuilder.Entity("LuanVan.Model.NguoiNhanCap3", b =>
                {
                    b.Property<int>("MaNguoiNhanCap3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiNhanCap3"));

                    b.Property<string>("DiaChiNguoiNhanCap3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<long>("MaXaPhuong")
                        .HasColumnType("bigint");

                    b.Property<string>("SoDienThoaiNguoiNhanCap3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhanCap3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiNhanCap3");

                    b.HasIndex("MaNguoiNhan");

                    b.HasIndex("MaXaPhuong");

                    b.ToTable("NguoiNhanCap3");
                });

            modelBuilder.Entity("LuanVan.Model.QuanHuyen", b =>
                {
                    b.Property<long>("MaQuanHuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaQuanHuyen"));

                    b.Property<int?>("MaTinhThanhPho")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanHuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaQuanHuyen");

                    b.HasIndex("MaTinhThanhPho");

                    b.ToTable("QuanHuyen");
                });

            modelBuilder.Entity("LuanVan.Model.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyen");
                });

            modelBuilder.Entity("LuanVan.Model.SoDiaChi", b =>
                {
                    b.Property<int>("MaSoDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSoDiaChi"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("MaXaPhuong")
                        .HasColumnType("bigint");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSoDiaChi");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("MaXaPhuong");

                    b.ToTable("SoDiaChi");
                });

            modelBuilder.Entity("LuanVan.Model.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeXacNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("HoatDong")
                        .HasColumnType("bit");

                    b.Property<byte[]>("MaBam")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("LuanVan.Model.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("LuanVan.Model.TinhThanhPho", b =>
                {
                    b.Property<int>("MaTinhThanhPho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinhThanhPho"));

                    b.Property<string>("TenTinhThanhPho")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTinhThanhPho");

                    b.ToTable("TinhThanhPho");
                });

            modelBuilder.Entity("LuanVan.Model.TrangThaiDonHang", b =>
                {
                    b.Property<int>("MaTrangThaiDonVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThaiDonVanChuyen"));

                    b.Property<string>("MoTaTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThaiDonVanChuyen");

                    b.ToTable("TrangThaiDonVanChuyen");
                });

            modelBuilder.Entity("LuanVan.Model.TrongLuong", b =>
                {
                    b.Property<int>("MaTrongLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrongLuong"));

                    b.Property<float>("PhiNhanVienGiaoHang")
                        .HasColumnType("real");

                    b.Property<float>("TrongLuongBatDau")
                        .HasColumnType("real");

                    b.Property<float>("TrongLuongKetThuc")
                        .HasColumnType("real");

                    b.HasKey("MaTrongLuong");

                    b.ToTable("TrongLuong");
                });

            modelBuilder.Entity("LuanVan.Model.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("LuanVan.Model.XaPhuong", b =>
                {
                    b.Property<long>("MaXaPhuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaXaPhuong"));

                    b.Property<long>("MaQuanHuyen")
                        .HasColumnType("bigint");

                    b.Property<string>("TenXaPhuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaXaPhuong");

                    b.HasIndex("MaQuanHuyen");

                    b.ToTable("XaPhuong");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietCuocPhi", b =>
                {
                    b.HasOne("LuanVan.Model.CuocPhi", "CuocPhi")
                        .WithMany("ChiTietCuocPhis")
                        .HasForeignKey("MaCuocPhi")
                        .IsRequired();

                    b.HasOne("LuanVan.Model.QuanHuyen", "QuanHuyen")
                        .WithMany("ChiTietCuocPhis")
                        .HasForeignKey("MaQuanHuyen")
                        .IsRequired();

                    b.Navigation("CuocPhi");

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietDonVanChuyen", b =>
                {
                    b.HasOne("LuanVan.Model.DonVanChuyen", "DonVanChuyen")
                        .WithMany("ChiTietDonVanChuyens")
                        .HasForeignKey("MaDonVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.LoaiMatHang", "LoaiMathang")
                        .WithMany("ChiTietDonVanChuyens")
                        .HasForeignKey("MaLoaiMatHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVanChuyen");

                    b.Navigation("LoaiMathang");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietTrangThai", b =>
                {
                    b.HasOne("LuanVan.Model.DonVanChuyen", "DonVanChuyen")
                        .WithMany("ChiTietTrangThais")
                        .HasForeignKey("MaDonVanChuyen")
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TrangThaiDonHang", "TrangThaiDonHang")
                        .WithMany("ChiTietTrangThais")
                        .HasForeignKey("MaTrangThaiDonVanChuyen")
                        .IsRequired();

                    b.Navigation("DonVanChuyen");

                    b.Navigation("TrangThaiDonHang");
                });

            modelBuilder.Entity("LuanVan.Model.ChiTietVaiTro", b =>
                {
                    b.HasOne("LuanVan.Model.Quyen", "Quyen")
                        .WithMany("VaiTros")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.VaiTro", "VaiTro")
                        .WithMany("Quyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("LuanVan.Model.CoVaiTro", b =>
                {
                    b.HasOne("LuanVan.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("VaiTros")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("LuanVan.Model.CuocPhi", b =>
                {
                    b.HasOne("LuanVan.Model.HinhThucVanChuyen", "HinhThucVanChuyen")
                        .WithMany("CuocPhi")
                        .HasForeignKey("MaHinhThucVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TrongLuong", "TrongLuong")
                        .WithMany("CuocPhiList")
                        .HasForeignKey("MaTrongLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThucVanChuyen");

                    b.Navigation("TrongLuong");
                });

            modelBuilder.Entity("LuanVan.Model.DonVanChuyen", b =>
                {
                    b.HasOne("LuanVan.Model.BaoHiemDonVanChuyen", "BaoHiemDonVanChuyen")
                        .WithMany("DonVanChuyens")
                        .HasForeignKey("MaBaoHiemDonVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TaiKhoan", "KhachHang")
                        .WithMany("DonVanChuyens")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TaiKhoan", "NhanVienGiaoHang")
                        .WithMany("DonNhanGiaos")
                        .HasForeignKey("MaNhanVienGiaoHang");

                    b.HasOne("LuanVan.Model.TaiKhoan", "QuanLy")
                        .WithMany("DonDuyets")
                        .HasForeignKey("MaQuanLy");

                    b.HasOne("LuanVan.Model.XaPhuong", "XaPhuong")
                        .WithMany()
                        .HasForeignKey("XaPhuongMaXaPhuong");

                    b.Navigation("BaoHiemDonVanChuyen");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVienGiaoHang");

                    b.Navigation("QuanLy");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("LuanVan.Model.DuLieuTinhCuoc", b =>
                {
                    b.HasOne("LuanVan.Model.HinhThucVanChuyen", "HinhThucVanChuyen")
                        .WithMany()
                        .HasForeignKey("MaHinhThucVanChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TinhThanhPho", "TinhThanhPho")
                        .WithMany("DuLieuTinhCuoc")
                        .HasForeignKey("MaTinhThanhPho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThucVanChuyen");

                    b.Navigation("TinhThanhPho");
                });

            modelBuilder.Entity("LuanVan.Model.MatHangCaNhan", b =>
                {
                    b.HasOne("LuanVan.Model.LoaiMatHang", "LoaiMatHang")
                        .WithMany("MatHangCaNhans")
                        .HasForeignKey("MaLoaiMatHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("MatHangCaNhans")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMatHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LuanVan.Model.NguoiNhanCaNhan", b =>
                {
                    b.HasOne("LuanVan.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("NguoiNhans")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Model.XaPhuong", "XaPhuong")
                        .WithMany()
                        .HasForeignKey("MaXaPhuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("LuanVan.Model.NguoiNhanCap3", b =>
                {
                    b.HasOne("LuanVan.Model.NguoiNhanCaNhan", "NguoiNhanCaNhan")
                        .WithMany("NguoiNhanCap3s")
                        .HasForeignKey("MaNguoiNhan")
                        .IsRequired();

                    b.HasOne("LuanVan.Model.XaPhuong", "XaPhuong")
                        .WithMany("NguoiNhanCap3s")
                        .HasForeignKey("MaXaPhuong")
                        .IsRequired();

                    b.Navigation("NguoiNhanCaNhan");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("LuanVan.Model.QuanHuyen", b =>
                {
                    b.HasOne("LuanVan.Model.TinhThanhPho", "TinhThanhPho")
                        .WithMany("QuanHuyens")
                        .HasForeignKey("MaTinhThanhPho");

                    b.Navigation("TinhThanhPho");
                });

            modelBuilder.Entity("LuanVan.Model.SoDiaChi", b =>
                {
                    b.HasOne("LuanVan.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("DiaChis")
                        .HasForeignKey("MaTaiKhoan");

                    b.HasOne("LuanVan.Model.XaPhuong", "XaPhuong")
                        .WithMany()
                        .HasForeignKey("MaXaPhuong");

                    b.Navigation("TaiKhoan");

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("LuanVan.Model.ThongBao", b =>
                {
                    b.HasOne("LuanVan.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LuanVan.Model.XaPhuong", b =>
                {
                    b.HasOne("LuanVan.Model.QuanHuyen", "QuanHuyen")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("MaQuanHuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("LuanVan.Model.BaoHiemDonVanChuyen", b =>
                {
                    b.Navigation("DonVanChuyens");
                });

            modelBuilder.Entity("LuanVan.Model.CuocPhi", b =>
                {
                    b.Navigation("ChiTietCuocPhis");
                });

            modelBuilder.Entity("LuanVan.Model.DonVanChuyen", b =>
                {
                    b.Navigation("ChiTietDonVanChuyens");

                    b.Navigation("ChiTietTrangThais");
                });

            modelBuilder.Entity("LuanVan.Model.HinhThucVanChuyen", b =>
                {
                    b.Navigation("CuocPhi");
                });

            modelBuilder.Entity("LuanVan.Model.LoaiMatHang", b =>
                {
                    b.Navigation("ChiTietDonVanChuyens");

                    b.Navigation("MatHangCaNhans");
                });

            modelBuilder.Entity("LuanVan.Model.NguoiNhanCaNhan", b =>
                {
                    b.Navigation("NguoiNhanCap3s");
                });

            modelBuilder.Entity("LuanVan.Model.QuanHuyen", b =>
                {
                    b.Navigation("ChiTietCuocPhis");

                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("LuanVan.Model.Quyen", b =>
                {
                    b.Navigation("VaiTros");
                });

            modelBuilder.Entity("LuanVan.Model.TaiKhoan", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("DonDuyets");

                    b.Navigation("DonNhanGiaos");

                    b.Navigation("DonVanChuyens");

                    b.Navigation("MatHangCaNhans");

                    b.Navigation("NguoiNhans");

                    b.Navigation("ThongBaos");

                    b.Navigation("VaiTros");
                });

            modelBuilder.Entity("LuanVan.Model.TinhThanhPho", b =>
                {
                    b.Navigation("DuLieuTinhCuoc");

                    b.Navigation("QuanHuyens");
                });

            modelBuilder.Entity("LuanVan.Model.TrangThaiDonHang", b =>
                {
                    b.Navigation("ChiTietTrangThais");
                });

            modelBuilder.Entity("LuanVan.Model.TrongLuong", b =>
                {
                    b.Navigation("CuocPhiList");
                });

            modelBuilder.Entity("LuanVan.Model.VaiTro", b =>
                {
                    b.Navigation("Quyens");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("LuanVan.Model.XaPhuong", b =>
                {
                    b.Navigation("NguoiNhanCap3s");
                });
#pragma warning restore 612, 618
        }
    }
}
